"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var year = 1976;
// year = false;
console.log(year);
var age = 0x2b;
console.log(age);
var name = 'Ham';
// name = 10;
console.log(name);
